### ISSUE TITLE
[BUG] Inexistent words in dictionary source

### ISSUE THREAD

**Issue by Chaitanyabsprip** [Chaitanyabsprip/dictionaryCLI#17]
**Bug**
Searching for words that don't exist causes the program to exit with an error. 

**To Reproduce**
Search for word "mie"

**Expected behavior**
When searching for words that don't exist in the dictionary source, the program should notify with a message like "No meaning found".

**Screenshots**
![WhatsApp Image 2021-07-05 at 10 49 37 AM](https://user-images.githubusercontent.com/55058351/124422026-3e8e5600-dd80-11eb-974e-489e406ab21d.jpeg)
![WhatsApp Image 2021-07-05 at 10 49 37 AM(1)](https://user-images.githubusercontent.com/55058351/124422029-40581980-dd80-11eb-9cc8-998e4aa3b98a.jpeg)

**Desktop (please complete the following information):**
 - OS: Android 10 aarch
 - Version: 0.1.dev114+g7b46b19
 - Terminal: Termux

**Comment by gsiddhant159** [comment]
Fixed in #2035236502d172b7e4f715f21b6a22f736dc5297
